version: "3"

services:
  proxy:
    depends_on:
      - nginx
      - fastapi
    image: nginx:alpine
    container_name: 3m-proxyserver 
    restart: always 
    ports:
      - "81:80"
      # - "443:443"
    volumes:
      - ./proxyserver/nginx.conf:/etc/nginx/nginx.conf
      # - ../jsy/certbot:/etc/letsencrypt
      - ./webpage:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: 3m-webpage
    restart: always
    volumes:
      - ./webpage:/usr/share/nginx/html

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    container_name: 3m-api
    command: uvicorn main:app --host 0.0.0.0 --port 80
