services:
  proxy:
    depends_on:
      - nginx
      - fastapi
    image: nginx:alpine
    container_name: 3m-proxyserver 
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxyserver/nginx.conf:/etc/nginx/nginx.conf
      - ./webpage:/usr/share/nginx/html
      - ./certbot:/etc/letsencrypt

  nginx:
    image: nginx:latest
    container_name: 3m-webpage
    restart: always
    volumes:
      - ./webpage:/usr/share/nginx/html

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    container_name: 3m-api
    command: uvicorn main:app --host 0.0.0.0 --port 80

  certbot:
    depends_on:
      - proxy
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./webpage:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email test@test.com --agree-tos --no-eff-email --keep-until-expiring -d mkai.p-e.kr